import dns from 'node:dns';
dns.setServers(['8.8.8.8', '8.8.4.4']);


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "@/Component/Navber";
import Footer from "@/Component/Footer";
import NextThemeProvider from "@/Provider/nextThemeProvider";
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <NextThemeProvider>
          <Navber />
          <main> 
            {children}
            </main>
          <Footer />
        </NextThemeProvider>
         <ToastContainer
          position="top-right"
          autoClose={3000}
        />
      </body>
    </html>
  );
}
